services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    container_name: kolobok_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.dev.ini:/usr/local/etc/php/php.ini
    networks:
      - kolobok_network
    environment:
      - XDEBUG_CONFIG=client_host=172.29.48.1 client_port=9003 idekey=PHPSTORM
    depends_on:
      - mysql

  nginx:
    image: nginx:stable
    container_name: kolobok_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BACKEND_ADDRESS=app:9000
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - kolobok_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: kolobok_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: syc53Kwe6FPxyr*66
      MYSQL_DATABASE: cdnhub
      MYSQL_USER: kolobok
      MYSQL_PASSWORD: kolobok123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - kolobok_network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: kolobok_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kolobok_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  kolobok_network:
    driver: bridge
